on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

name: Update bucket
jobs:
  update:
    name: ♻ Update manifests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: foosel/scoop-checkver-action@main
        with:
          bucket: bucket
          force: force
      - uses: EndBug/add-and-commit@v7
        with:
          message: "Updated manifests..."
          author_name: 'github-actions[bot]'
          author_email: 'github-actions[bot]@users.noreply.github.com'
